# Generated by Django 2.2.12 on 2022-10-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlockNumber', models.IntegerField()),
                ('docBalanceBefore', models.IntegerField()),
                ('paBalanceBefore', models.IntegerField()),
                ('docBalanceAfter', models.IntegerField()),
                ('paBalanceAfter', models.IntegerField()),
                ('hexTrans', models.CharField(max_length=150)),
                ('loadTrans', models.CharField(max_length=550)),
            ],
        ),
    ]
