# Generated by Django 4.1.1 on 2022-11-17 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runCrosschain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transition',
            old_name='docBalanceAfter',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='transition',
            name='docBalanceBefore',
        ),
        migrations.RemoveField(
            model_name='transition',
            name='paBalanceAfter',
        ),
        migrations.RemoveField(
            model_name='transition',
            name='paBalanceBefore',
        ),
    ]
